---
# this file is to be used to set-up the backend server for the easy-scrabble
# it assumes that ssh public key is for user scrabble is already set-up and the scrabble user as sudo
# privileges already on the target server(s)
- name: provisioning for scrabble server backend on ubuntu 18.04 LTS
  hosts: ovh   # server must be defined in /etc/ansible/hosts file
  remote_user: scrabble  # user must be pre-configures with sudo privileges
  become: yes

  tasks:
    - name: install python 3.6 and virtualenv with system packaging which is better than pip
      apt:
        name:
        - python3.6
        - virtualenv
        state: latest

    - name: install python modules
      pip:
        virtualenv_python: python3.6
        virtualenv: /scrabble_venv
        name:
#          - marshmallow
          - hug
#          - line_profiler   compilation failing because /python.h/ not found at compile time
          - zmq
          - waitress
          - typing
# latest marshmallow version - 3.0.0xxx mandatory
          - git+https://github.com/marshmallow-code/marshmallow.git@dev
          - pytest


    - name: install nginx
      apt:
        name: nginx
        state: latest
      notify: start nginx

    - name: Creates directories for default nginx html pages and ssl conf
      file:
        path:
        - /scrabble/html
        - /etc/ssl/certs/
        - /etc/ssl/private/
        state: directory

    - name: copy default html page
      copy:
        src: "/mnt/e/Thib/src/scrabble-ovh-vagrant/scrabble.html"
        dest: "/scrabble/html"
        remote_src: no

    - name: copy private key
      copy:
        src: "/mnt/e/Thib/src/scrabble-ovh-vagrant/scrabble-backend-selfsigned.key"
        dest: "/etc/ssl/private"
        remote_src: no

    - name: copy self signed certificate
      copy:
        src: "/mnt/e/Thib/src/scrabble-ovh-vagrant/scrabble-backend-selfsigned.crt"
        dest: "/etc/ssl/certs"
        remote_src: no
      notify: restart nginx

    - name: copy Diffie-Hellman group
      copy:
        src: "/mnt/e/Thib/src/scrabble-ovh-vagrant/dhparam.pem"
        dest: "/etc/nginx"
        remote_src: no
      notify: restart nginx

    - name: set nginx conf
      copy:
        src: "/mnt/e/Thib/src/scrabble-ovh-vagrant/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        remote_src: no
      notify: restart nginx

    # copy source code from github repo TODO make the repo private
    - git:
        repo: 'https://github.com/thib38/easy-scrabble-backend.git'
        dest: /scrabble_venv/src
        version: master
        force: yes
# - name: set french keyboard
#      command: loadkeys fr
#      register: french_keyboard

    - name: Creates directory for various scrabble application logs
      file:
        path: /var/log/scrabble
        state: directory

    - name: activate virtualenv
      shell: |
       cd /scrabble_venv/src
       nohup /scrabble_venv/bin/python dictionnary_server_en.py &
       nohup /scrabble_venv/bin/python dictionary_server_fr.py &
       nohup /scrabble_venv/bin/python waitress_launch.py &cd  é
       exit 0
      register: venv_activate

    - name: print output
      debug:
        var: venv_activate
        verbosity: 0

    - name: install ufw
      apt:
        name: ufw
        state: latest


  handlers:
    - name: start nginx
      service: name=nginx state=started
    - name: restart nginx
      service: name=nginx state=restarted